# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0b2c803c0d8cb2de39efb2a079040b93821f9ffbab670d4b9cad8a167da60c77b184abaf3b1ae386d1063dcc3c57771ce8f4f7b0db5848681c1aef9fecf64f2

test:
  secret_key_base: ed32d503efe6a766dcf1f07dfb3d4253188fbef0dc41448af067ab6cbcd42bbde04821d57106e365e081d62a89c32a6354b2995ac65bf7e38f599036ecd69d81

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
